name: Tofu Test Suites

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  tofu-test-unit:
    name: OpenTofu Test (Unit)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

      - name: Run unit tests
        uses: ./
        with:
          workdir: test/valid
          steps: test
          test-dir: tests/unit
          skip-plan-upload: true
          comment-mode: off

  tofu-test-integration:
    name: OpenTofu Test (Integration)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

      - name: Run integration tests
        uses: ./
        with:
          workdir: test/valid
          steps: test
          test-dir: tests/integration
          skip-plan-upload: true
          comment-mode: off
